stages:
  - release

release_job:
  stage: release
  only:
    - main
  script:
    - RELEASE_VERSION=$(cat .release-version)
    - RELEASE_NAME="Release $RELEASE_VERSION"
    - RELEASE_NOTE="Release notes for version $RELEASE_VERSION"
    - echo "Token: ${GITLAB_PRIVATE_TOKEN}"
    - git tag $RELEASE_VERSION
    - git push https://oauth2:${GITLAB_PRIVATE_TOKEN}@gitlab.com/uberlogger/uberlogger-stm32.git --tags -o ci.skip

    # Create a release using GitLab's API.
    - |
      curl --header "PRIVATE-TOKEN: ${GITLAB_PRIVATE_TOKEN}" \
           --header "Content-Type: application/json" \
           -X POST "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/releases" \
           --data '{
             "name": "'"$RELEASE_NAME"'",
             "tag_name": "'"$RELEASE_VERSION"'",
             "description": "'"$RELEASE_NOTE"'",
             "assets": {
               "links": [{
                 "name": "ota_support.bin",
                 "url": "'"$CI_PROJECT_URL"'/-/jobs/artifacts/'"$CI_COMMIT_REF_NAME"'/raw/ota_support.bin?job=release_job"
               }]
             }
           }'
  artifacts:
    paths:
      - ota_support.bin
