#ifndef _EVENTS_H
#define _EVENTS_H

#include "stdint.h"

typedef enum uint8_t {
	EVENT_ADC_IS_HALF= 0x00,
	EVENT_ADC_IS_FULL,
	EVENT_ADC_STOPPED,
	EVENT_ADC_OVERRUN,
	EVENT_CONFIG_ENTER_HANDLER,
	EVENT_CONFIG_EXIT_HANDLER,
	EVENT_SPI_MSG_RECEIVED,
	EVENT_SPI_MSG_SENT,
	EVENT_SPI_MSG_RX_TIMEOUT,
	EVENT_SPI_MSG_TX_TIMEOUT
} events_t;


#endif
